
---
version: '3'
services:
    web:
      build: .
      command: bash -c "bundle exec puma -C config/puma.rb"
      volumes:
        - .:/ruterocl
      ports:
        - "3000:3000"
      # depends_on:
      #   - db
      env_file:
        - ./.env
